name: pasikuthu
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  sign_in_button: ^3.0.0
  firebase_core: ^1.24.0
  progress_dialog_null_safe: ^1.0.7
  firebase_auth: ^3.11.0
  cloud_firestore: ^3.5.0
  location: ^4.4.0
  google_sign_in: ^5.4.2
  email_validator: ^2.1.17
  open_mail_app: ^0.4.5
  csc_picker: ^0.2.6
  flutter_neumorphic: ^3.2.0
  provider: ^6.0.4
  image_picker: ^0.8.6
  cross_file_image: ^1.0.0
  geocoding: ^2.0.5
  firebase_storage: ^10.3.11
  galleryimage: ^1.2.0
  photo_view: ^0.14.0
  google_maps_flutter: ^2.2.1
  map_launcher: ^2.4.0
  url_launcher: ^6.1.6
  search_page: ^2.2.0
  chat_bubbles: ^1.3.1
  custom_pop_up_menu: ^1.2.4
  carousel_slider: ^4.1.1
  swipe_image_gallery: ^0.8.0
  animated_widgets: ^1.1.0
  geocoder2: ^1.4.0
  location_geocoder: ^1.0.5
  internet_connection_checker: ^1.0.0+1
  overlay_support: ^2.1.0






dev_dependencies:
  flutter_launcher_icons: ^0.10.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/1024.png"

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Bold.ttf
      - asset: assets/fonts/Lato-Regular.ttf
        weight: 700
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
